-- Baseline of the schema Hibernate produced while the project ran with ddl-auto=update.
-- From here on the database is owned by these migrations and Hibernate only validates.
-- Generated from the JPA metadata against PostgreSQL 16, then formatted and given stable
-- constraint names. See docs/migrations.md for the conventions.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(120) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ux_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'OPERATOR', 'CUSTOMER'))
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(80) NOT NULL,
    slug        VARCHAR(80) NOT NULL,
    description VARCHAR(300),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT ux_categories_name UNIQUE (name),
    CONSTRAINT ux_categories_slug UNIQUE (slug)
);

CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sku               VARCHAR(40)  NOT NULL,
    name              VARCHAR(150) NOT NULL,
    description       VARCHAR(2000),
    brand             VARCHAR(80),
    image_url         VARCHAR(500),
    price             NUMERIC(12, 2) NOT NULL,
    compare_at_price  NUMERIC(12, 2),
    status            VARCHAR(20) NOT NULL,
    category_id       BIGINT      NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT ux_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'DRAFT', 'ARCHIVED')),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX ix_products_category ON products (category_id);
CREATE INDEX ix_products_status ON products (status);

CREATE TABLE inventory_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id    BIGINT  NOT NULL,
    on_hand       INTEGER NOT NULL,
    reserved      INTEGER NOT NULL,
    reorder_point INTEGER NOT NULL,
    version       BIGINT  NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_inventory_items PRIMARY KEY (id),
    CONSTRAINT ux_inventory_items_product UNIQUE (product_id),
    CONSTRAINT fk_inventory_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE stock_movements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id       BIGINT      NOT NULL,
    type             VARCHAR(20) NOT NULL,
    quantity         INTEGER     NOT NULL,
    on_hand_after    INTEGER     NOT NULL,
    reserved_after   INTEGER     NOT NULL,
    reference        VARCHAR(60),
    reason           VARCHAR(200),
    created_by       VARCHAR(80) NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_stock_movements PRIMARY KEY (id),
    CONSTRAINT ck_stock_movements_type
        CHECK (type IN ('RECEIPT', 'ADJUSTMENT', 'RESERVATION', 'RELEASE', 'SALE')),
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX ix_movements_product_created ON stock_movements (product_id, created_at);
CREATE INDEX ix_movements_type_created ON stock_movements (type, created_at);

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_number   VARCHAR(30)  NOT NULL,
    customer_email VARCHAR(120) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    total          NUMERIC(12, 2) NOT NULL,
    version        BIGINT       NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at     TIMESTAMP(6) WITH TIME ZONE,
    paid_at        TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT ux_orders_number UNIQUE (order_number),
    CONSTRAINT ck_orders_status CHECK (status IN
        ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED'))
);

CREATE INDEX ix_orders_customer ON orders (customer_email);
CREATE INDEX ix_orders_status_created ON orders (status, created_at);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id     BIGINT       NOT NULL,
    product_id   BIGINT       NOT NULL,
    sku          VARCHAR(40)  NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    quantity     INTEGER      NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    line_total   NUMERIC(12, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE import_jobs (
    id             VARCHAR(36) NOT NULL,
    file_name      VARCHAR(255),
    status         VARCHAR(20)  NOT NULL,
    total_rows     INTEGER      NOT NULL,
    processed_rows INTEGER      NOT NULL,
    created        INTEGER      NOT NULL,
    updated        INTEGER      NOT NULL,
    failed         INTEGER      NOT NULL,
    errors         VARCHAR(4000),
    created_by     VARCHAR(120) NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    finished_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_import_jobs PRIMARY KEY (id),
    CONSTRAINT ck_import_jobs_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor       VARCHAR(120) NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    entity_type VARCHAR(60),
    entity_id   VARCHAR(60),
    details     VARCHAR(1000),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE INDEX ix_audit_created ON audit_logs (created_at);
CREATE INDEX ix_audit_entity ON audit_logs (entity_type, entity_id);
