-- Email ownership and password recovery.
-- Tokens are stored as a SHA-256 hash: a dump of this table cannot be used to take over an account,
-- the same reason passwords are not stored either. The plain token exists only in the message sent
-- to the address being proved.

ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN email_verified_at TIMESTAMP(6) WITH TIME ZONE;

-- Accounts that existed before this migration were created by an operator, not self-registered.
UPDATE users SET email_verified = TRUE, email_verified_at = created_at;

CREATE TABLE auth_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    purpose    VARCHAR(30)  NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_auth_tokens PRIMARY KEY (id),
    CONSTRAINT ux_auth_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_auth_tokens_purpose CHECK (purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')),
    CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_auth_tokens_user_purpose ON auth_tokens (user_id, purpose);
CREATE INDEX ix_auth_tokens_expires ON auth_tokens (expires_at);
