-- Second factor for staff accounts.
-- The shared secret is the credential here, so it is encrypted at rest by the application before it
-- reaches this column. Recovery codes are stored hashed, like passwords, and are single use.

ALTER TABLE users
    ADD COLUMN totp_secret VARCHAR(255),
    ADD COLUMN totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN totp_enrolled_at TIMESTAMP(6) WITH TIME ZONE;

CREATE TABLE recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL,
    code_hash  VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_recovery_codes PRIMARY KEY (id),
    CONSTRAINT ux_recovery_codes_hash UNIQUE (code_hash),
    CONSTRAINT fk_recovery_codes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_recovery_codes_user ON recovery_codes (user_id);
