-- Consent ledger for Ley 1581 de 2012 and Decreto 1377 de 2013.
-- Append only: granting and revoking both add a row, so the record shows what was agreed, when, from
-- where and against which version of the policy. A column that is overwritten proves nothing.

CREATE TABLE consents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT       NOT NULL,
    purpose        VARCHAR(40)  NOT NULL,
    granted        BOOLEAN      NOT NULL,
    policy_version VARCHAR(20)  NOT NULL,
    source         VARCHAR(40)  NOT NULL,
    -- Hashed, because the address is itself personal data and only needs to be comparable.
    ip_hash        VARCHAR(64),
    user_agent     VARCHAR(255),
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_consents PRIMARY KEY (id),
    CONSTRAINT ck_consents_purpose CHECK (purpose IN
        ('DATA_PROCESSING', 'MARKETING_EMAIL', 'MARKETING_WHATSAPP', 'ANALYTICS')),
    CONSTRAINT fk_consents_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_consents_user_purpose ON consents (user_id, purpose, created_at DESC);

ALTER TABLE users
    ADD COLUMN anonymized_at TIMESTAMP(6) WITH TIME ZONE;
